---
galaxy_info:
  role_name: ntp_client
  author: vladdarkstalker
  description: Configure a Chrony NTP client on Debian-based systems
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

