---
galaxy_info:
  role_name: nginx
  author: vladdarkstalker
  description: Configure an Nginx HTTP content server on Debian-based systems
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

