---
- name: Install Nexus runtime packages
  ansible.builtin.package:
    name: "{{ nexus_packages }}"
    state: present

- name: Create Nexus system group
  ansible.builtin.group:
    name: "{{ nexus_group }}"
    system: true
    state: present

- name: Create Nexus system user
  ansible.builtin.user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: Create Nexus installation root
  ansible.builtin.file:
    path: "{{ nexus_install_root }}"
    state: directory
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    mode: u=rwx,g=rx,o=rx

- name: Download Nexus distribution archive
  ansible.builtin.get_url:
    url: "{{ nexus_download_url }}"
    dest: "{{ nexus_download_path }}"
    checksum: "{{ nexus_download_checksum }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Extract Nexus distribution archive
  ansible.builtin.unarchive:
    src: "{{ nexus_download_path }}"
    dest: "{{ nexus_install_root }}"
    remote_src: true
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    creates: "{{ nexus_install_directory }}/bin/nexus"

- name: Link active Nexus installation
  ansible.builtin.file:
    src: "{{ nexus_install_directory }}"
    dest: "{{ nexus_install_link }}"
    state: link
    force: true
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"

