---
argument_specs:
  main:
    short_description: Configure a TFTP server
    options:
      tftp_user:
        type: str
        required: true
      tftp_group:
        type: str
        required: true
      tftp_packages:
        type: list
        elements: str
        required: true
      tftp_root:
        type: path
        required: true
      tftp_address:
        type: str
        required: true
      tftp_options:
        type: str
        required: true
      tftp_backup_path:
        type: path
        required: true
      tftp_backup_files:
        type: list
        elements: path
        required: true

