---
galaxy_info:
  role_name: nexus
  author: vladdarkstalker
  description: Install Nexus Repository Manager on Debian-based systems
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

