---
# Enable time synchronization for the current session and future boots.
- name: Enable and start Chrony server
  ansible.builtin.systemd_service:
    name: "{{ ntp_server_service_name }}"
    enabled: true
    state: started
