---
galaxy_info:
  role_name: nfs_server
  author: vladdarkstalker
  description: Configure an NFS server export on Debian-based systems
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

