---
# Configure all PXE providers on the same host and enable DHCP last.
- name: Configure PXE server
  hosts: pxe_servers
  become: true
  gather_facts: true

  vars_files:
    - vars/pxe.yaml

  roles:
    - role: ../roles/pxe
